
import { Content, ContentType } from './types';

// Fix: Renamed ContentItem to Content and updated MOCK_CONTENT to match Content interface from types.ts
export const MOCK_CONTENT: Content[] = [
  {
    id: '1',
    title: 'الحشاشين',
    description: 'قصة حسن الصباح وجماعة الحشاشين في القرن الحادي عشر.',
    type: ContentType.Series,
    poster: 'https://picsum.photos/seed/hash1/300/450',
    backdrop: 'https://picsum.photos/seed/hash1/1920/1080',
    rating: 4.8,
    ageRating: 'PG-15',
    categories: ['مسلسلات عربية'],
    genres: ['دراما', 'تاريخي'],
    releaseYear: 2024,
    cast: [],
    visibility: 'general',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'كامل العدد +1',
    description: 'استكمال لمغامرات عائلة ليلى وأحمد بعد زيادة عدد أفراد الأسرة.',
    type: ContentType.Series,
    poster: 'https://picsum.photos/seed/kamel/300/450',
    backdrop: 'https://picsum.photos/seed/kamel/1920/1080',
    rating: 4.2,
    ageRating: 'G',
    categories: ['مسلسلات عربية'],
    genres: ['كوميديا'],
    releaseYear: 2024,
    cast: [],
    visibility: 'general',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'كيرة والجن',
    description: 'يرصد الفيلم حالة الغليان التي كان يموج بها الشارع المصري بالتزامن مع اندلاع ثورة 1919.',
    type: ContentType.Movie,
    poster: 'https://picsum.photos/seed/kira/300/450',
    backdrop: 'https://picsum.photos/seed/kira/1920/1080',
    rating: 4.7,
    ageRating: 'PG-13',
    categories: ['افلام عربية'],
    genres: ['أكشن', 'تاريخي'],
    releaseYear: 2022,
    cast: [],
    visibility: 'general',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'بيت الروبي',
    description: 'إبراهيم الروبي يقرر الخروج من عزلته والعودة للقاهرة لمواجهة تحديات جديدة.',
    type: ContentType.Movie,
    poster: 'https://picsum.photos/seed/ruby/300/450',
    backdrop: 'https://picsum.photos/seed/ruby/1920/1080',
    rating: 4.0,
    ageRating: 'G',
    categories: ['افلام عربية'],
    genres: ['كوميديا'],
    releaseYear: 2023,
    cast: [],
    visibility: 'general',
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'جعفر العمدة',
    description: 'رحلة بحث جعفر العمدة عن ابنه المفقود منذ سنوات طويلة.',
    type: ContentType.Series,
    poster: 'https://picsum.photos/seed/jaafar/300/450',
    backdrop: 'https://picsum.photos/seed/jaafar/1920/1080',
    rating: 4.5,
    ageRating: 'PG-15',
    categories: ['مسلسلات عربية'],
    genres: ['دراما'],
    releaseYear: 2023,
    cast: [],
    visibility: 'general',
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'تحت الوصاية',
    description: 'كفاح أرملة من أجل حماية أولادها وإدارة مركب صيد زوجها الراحل.',
    type: ContentType.Series,
    poster: 'https://picsum.photos/seed/taht/300/450',
    backdrop: 'https://picsum.photos/seed/taht/1920/1080',
    rating: 4.6,
    ageRating: 'PG-13',
    categories: ['مسلسلات عربية'],
    genres: ['دراما'],
    releaseYear: 2023,
    cast: [],
    visibility: 'general',
    createdAt: new Date().toISOString(),
  }
];